# FWA Project
variables:
  PATH_DIR: "/apps/website"
  DEV_SSH_CON: "root@182.160.54.73"
  STAGE_SSH_CON: "root@110.239.86.194"
  PROD_SSH_CON: "root@110.239.95.84"
  COMPOSE_SRV: "fwa-website"
  CONT_NAME: "fwa_website_app"
  IMG_NAME: "fwa_website"
  DEV_VER: "devel"
  ENV_FILE: "/apps/fwa_website.env"
  CONT_PATH: "/app"
  COMPOSE_FILE: "/apps/docker-compose.yml"
  COMPOSE_SRV: "fwa-website"
  DEV_VER: "devel"
  STAGE_VER: "stage"
  PROD_VER: "prod"
  SSH_PORT: "9922"
  PROD_PORT: "3579"

stages:          # List of stages for jobs, and their order of execution
  - Release
  - Build
  - Test
  - Deploy
  - Push

#Add caching for "node_modules/" directory to speed up builds by reusing dependencies from cache.
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

devel-job:       # This job runs in the build stage, which runs first.
  stage: Build
  tags:
    - ira-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes:
        - Dockerfile
        - .env.devel
        - .env.stage
        - .env.prod
        #- .gitlab-ci.yml
      when: never   # Pipeline tidak akan berjalan jika file dalam 'changes' diubah.
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always # Pipeline akan berjalan jika file ada perubahan.
  before_script:
    - apk update && apk add --no-cache git curl vim openssh-client
    - mkdir -p ~/.ssh
    - echo "$FWA_DEV_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p $SSH_PORT $DEV_SSH_CON \
      "echo 'Development - Reset and clean the repository to avoid stale changes in container'; \
      cd $PATH_DIR; \
      git reset --hard; \
      git clean -fd; \
      echo 'Development - Fetch and reset to match the remote branch'; \
      git fetch --all; \
      git reset --hard origin/development; \
      echo 'Development - Local Repository in container was cleaned.'"
  script:
    - mkdir -p ~/.ssh
    - echo "Development - Compiling and update the Code..."
    - echo "$FWA_DEV_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p $SSH_PORT $DEV_SSH_CON \
      "echo "Development - Update code and Deployment starting"; \
        cd $PATH_DIR; \
        git pull origin development; \
        docker compose -f $COMPOSE_FILE down $COMPOSE_SRV; \
        docker rmi $IMG_NAME:$DEV_VER; \
        docker compose -f $COMPOSE_FILE build --no-cache $COMPOSE_SRV; \
        docker compose -f $COMPOSE_FILE up -d $COMPOSE_SRV; \
        docker ps -a | grep $CONT_NAME; \
        docker builder prune -a -f; \
        docker image prune -a -f; \
        docker exec -it $CONT_NAME sh -c 'npm ls && npm outdate && npm audit'; \
        echo 'Development - Docker Deployment Completed.'; \
      "
  artifacts:
    paths:
      - build/

staging-job:       # This job runs in the build stage, which runs first.
  stage: Build
  tags:
    - ira-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'
      changes:
        - Dockerfile
        - .env.devel
        - .env.stage
        - .env.prod
        - .gitlab-ci.yml
      when: never   # Pipeline tidak akan berjalan jika file dalam 'changes' diubah.
    - if: '$CI_COMMIT_BRANCH == "stage"'
      when: always # Pipeline akan berjalan jika file ada perubahan.
  before_script:
    - apk update && apk add --no-cache git curl vim openssh-client
    - mkdir -p ~/.ssh
    - echo "$FWA_STAGE_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p $SSH_PORT $STAGE_SSH_CON \
      "echo 'Staging - Reset and clean the repository to avoid stale changes in container'; \
      cd $PATH_DIR; \
      git reset --hard; \
      git clean -fd; \
      echo 'Staging - Fetch and reset to match the remote branch'; \
      git fetch --all; \
      git reset --hard origin/stage; \
      echo 'Staging - Local Repository in container was cleaned.'"
  script:
    - mkdir -p ~/.ssh
    - echo "Stage - Compiling and update the Code..."
    - echo "$FWA_STAGE_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p $SSH_PORT $STAGE_SSH_CON \
      "echo "Staging - Update code and Deployment starting"; \
        cd $PATH_DIR; \
        git pull origin stage; \
        docker compose -f $COMPOSE_FILE down $COMPOSE_SRV; \
        docker rmi $IMG_NAME:$STAGE_VER; \
        docker compose -f $COMPOSE_FILE build --no-cache $COMPOSE_SRV; \
        docker compose -f $COMPOSE_FILE up -d $COMPOSE_SRV; \
        docker ps -a | grep $CONT_NAME; \
        docker builder prune -a -f; \
        docker image prune -a -f; \
        docker exec -it $CONT_NAME sh -c 'npm ls && npm outdate && npm audit'; \
        echo 'Staging - Docker Deployment Completed.'; \
      "
  artifacts:
    paths:
      - build/

deploy-production:
  stage: Deploy
  tags:
    - ira-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - .env.devel
        - .env.stage
        - .env.prod
        - .gitlab-ci.yml
      when: never   # Pipeline tidak akan berjalan jika file dalam 'changes' diubah.
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always # Pipeline akan berjalan jika file ada perubahan.
  before_script:
    - apk update && apk add --no-cache git curl vim openssh-client
    - mkdir -p ~/.ssh
    - echo "$FWA_PROD_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p $PROD_PORT $PROD_SSH_CON \
      "echo 'Production - Reset and clean the repository to avoid stale changes in container'; \
      cd $PATH_DIR; \
      git reset --hard; \
      git clean -fd; \
      echo 'Production - Fetch and reset to match the remote branch'; \
      git fetch --all; \
      git reset --hard origin/main; \
      echo 'Production - Local Repository in container was cleaned.'"
  script:
    - mkdir -p ~/.ssh
    - echo "Production - Compiling and update the Code..."
    - echo "$FWA_PROD_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p $PROD_PORT $PROD_SSH_CON \
      "echo "Production - Update code and Deployment starting"; \
        cd $PATH_DIR; \
        git pull origin main; \
        docker compose -f $COMPOSE_FILE down fwa-website; \
        docker rmi fwa_website:$PROD_VER; \
        docker stop fwa_mitra_app_2 fwa_crm_app_2 fwa_cms_app_2 fwa_sales_app_2; \
        docker compose -f $COMPOSE_FILE build --no-cache fwa-website; \
        docker compose -f $COMPOSE_FILE up -d fwa-website; \
        docker ps -a | grep fwa_website_app; \
        docker builder prune -a -f; \
        docker image prune -a -f; \
        docker exec -it fwa_website_app sh -c 'npm ls && npm outdate && npm audit'; \
        echo 'Production - Container fwa_website_app has been updated.'; \
        echo 'Production - Updating Container fwa_website_app_2.'; \
        docker compose -f $COMPOSE_FILE down fwa-website-2; \
        docker rmi fwa_website_2:$PROD_VER; \
        docker compose -f $COMPOSE_FILE build --no-cache fwa-website-2; \
        docker compose -f $COMPOSE_FILE up -d fwa-website-2; \
        docker ps -a | grep fwa_website_app_2; \
        docker builder prune -a -f; \
        docker image prune -a -f; \
        docker exec -it fwa_website_app_2 sh -c 'npm ls && npm outdate && npm audit'; \
        echo 'Production - Container fwa_website_app_2 has been updated.'; \
        docker start fwa_mitra_app_2 fwa_crm_app_2 fwa_cms_app_2 fwa_sales_app_2; \
        echo 'Production - Docker Deployment Completed.'; \
      "
  artifacts:
    paths:
      - build/