# FWA Project
variables:
  #DEV_SSH_CON: "root@114.119.190.115"
  DEV_SSH_CON: "root@fwa-devel"
  STAGE_SSH_CON: "root@"
  PROD_SSH_CON: "root@"
  CONT_NAME: "fwa_website_app"
  REGISTRY_URL: "registry.gitlab.com/macroad-dev/ije-fwa_20072025/fe_web_ije-fwa_22072025"
  REPO_URL: "git@gitlab.com:macroad-dev/ije-fwa_20072025/fe_web_ije-fwa_22072025.git"
  DEV_VER: "devel"
  ENV_FILE: "/apps/fwa_website.env"
  CONT_PATH: "/app"
  COMPOSE_FILE: "/apps/docker-compose.yml"
  COMPOSE_SVC: "fwa-website"
  DEV_VER: "devel"
  STAGE_VER: "stage"
  PROD_VER: "prod"

stages:          # List of stages for jobs, and their order of execution
  - Release
  - Build
  - Test
  - Deploy
  - Push

#Add caching for "node_modules/" directory to speed up builds by reusing dependencies from cache.
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

devel-job:       # This job runs in the build stage, which runs first.
  stage: Build
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes:
        - Dockerfile
        - .env.devel
        - .env.stage
        - .env.prod
        ###- .gitlab-ci.yml
      when: never   # Pipeline will not running if the files are in the list was 'changes'.
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always # Pipeline will running if the files are not in the list was 'changes'.
  before_script:
    - apt update && apt install -y git
    - apt install -y vim
    - apt install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$FWA_DEV_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p 9922 $DEV_SSH_CON \
      "echo 'Development - Reset and clean the repository to avoid stale changes in container'; \
      docker exec $CONT_NAME git reset --hard; \
      docker exec $CONT_NAME git clean -fd; \
      echo 'Development - Fetch and reset to match the remote branch'; \
      docker exec $CONT_NAME git fetch --all; \
      docker exec $CONT_NAME git reset --hard origin/development; \
      echo 'Development - Local Repository in container was cleaned.'"
  script:
    - mkdir -p ~/.ssh
    - echo "Development - Compiling and update the Code..."
    - echo "$FWA_DEV_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p 9922 $DEV_SSH_CON \
      "docker ps --filter 'name=$CONT_NAME' --format '{{.Names}}' | grep -w $CONT_NAME > /dev/null; \
      if [ \$? -eq 0 ]; then \
        echo 'Development - Container $CONT_NAME is already running.'; \
        docker exec $CONT_NAME apt update; \
        docker exec $CONT_NAME apt install -y curl vim plocate iputils-ping net-tools openssh-client git; \
        docker exec $CONT_NAME sh -c "ssh-keyscan -H github.com > ~/.ssh/known_hosts"; \
        docker exec $CONT_NAME git config --global user.email 'rizal@weave.co.id'; \
        docker exec $CONT_NAME git config --global user.name 'rizal'; \
        docker exec $CONT_NAME git config --global credential.helper store; \
        docker exec $CONT_NAME git branch --set-upstream-to=origin/development development; \
        docker exec $CONT_NAME git pull origin development; \
        docker exec $CONT_NAME npm install; \
        docker exec $CONT_NAME npm i sharp; \
        docker exec $CONT_NAME env NODE_OPTIONS="--max_old_space_size=1024" npm run build --prod; \
        docker stop $CONT_NAME; \
        docker start $CONT_NAME; \
        echo 'Development - Docker Deployment Completed.'; \
      else \
        echo 'Development - Image $REGISTRY_URL:$DEV_VER not found, start building...'; \
        docker stop $CONT_NAME; \
        docker compose -f $COMPOSE_FILE down $COMPOSE_SVC; \
        docker compose -f $COMPOSE_FILE up -d --build $COMPOSE_SVC; \
        docker cp $ENV_FILE $CONT_NAME:$CONT_PATH/.env; \ 
        docker exec $CONT_NAME apt update && apt install -y curl vim plocate iputils-ping net-tools openssh-client git; \
        docker exec $CONT_NAME sh -c "ssh-keyscan -H github.com > ~/.ssh/known_hosts"; \
        docker exec $CONT_NAME git config --global user.email 'rizal@weave.co.id'; \
        docker exec $CONT_NAME git config --global user.name 'rizal'; \
        docker exec $CONT_NAME git config --global credential.helper store; \
        docker exec $CONT_NAME git branch --set-upstream-to=origin/development development; \
        docker exec $CONT_NAME git pull origin development; \
        docker exec $CONT_NAME npm install; \
        docker exec $CONT_NAME npm i sharp; \
        docker exec $CONT_NAME env NODE_OPTIONS="--max_old_space_size=1024" npm run build --prod; \
        docker stop $CONT_NAME; \
        docker start $CONT_NAME; \
        echo 'Development - Docker Deployment Completed.'; \
      fi"
  artifacts:
    paths:
      - build/

staging-job:       # This job runs in the build stage, which runs first.
  stage: Build
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'
      changes:
        - Dockerfile
        - .env.devel
        - .env.stage
        - .env.prod
        - .gitlab-ci.yml
      when: never   # Pipeline will not running if the files are in the list was 'changes'.
    - if: '$CI_COMMIT_BRANCH == "stage"'
      when: always # Pipeline will running if the files are in the list was 'changes'.
  before_script:
    - apt update && apt install -y git
    - apt install -y vim
    - apt install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$FWA_STAGE_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p 9922 $STAGE_SSH_CON \
      "echo 'Staging - Reset and clean the repository to avoid stale changes in container'; \
      docker exec $CONT_NAME git reset --hard; \
      docker exec $CONT_NAME git clean -fd; \
      echo 'Staging - Fetch and reset to match the remote branch'; \
      docker exec $CONT_NAME git fetch --all; \
      docker exec $CONT_NAME git reset --hard origin/stage; \
      echo 'Staging - Local Repository in container was cleaned.'"
  script:
    - echo "Staging - Compiling and update the Code in Docker..."
    - mkdir -p ~/.ssh
    - echo "$FWA_STAGE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p 9922 $STAGE_SSH_CON \
      "docker ps --filter 'name=$CONT_NAME' --format '{{.Names}}' | grep -w $CONT_NAME > /dev/null; \
      if [ \$? -eq 0 ]; then \
        echo 'Staging - Container $CONT_NAME is already running.'; \
        docker exec $CONT_NAME apt update; \
        docker exec $CONT_NAME apt update && apt install -y curl vim plocate iputils-ping net-tools openssh-client git; \
        docker exec $CONT_NAME sh -c "ssh-keyscan -H github.com > ~/.ssh/known_hosts"; \
        docker exec $CONT_NAME git config --global user.email 'rizal@weave.co.id'; \
        docker exec $CONT_NAME git config --global user.name 'rizal'; \
        docker exec $CONT_NAME git config --global credential.helper store; \
        docker exec $CONT_NAME git branch --set-upstream-to=origin/stage stage; \
        docker exec $CONT_NAME git pull origin stage; \
        docker exec $CONT_NAME npm install; \
        docker exec $CONT_NAME npm i sharp; \
        docker exec $CONT_NAME env NODE_OPTIONS="--max_old_space_size=1024" npm run build --prod; \
        docker stop $CONT_NAME; \
        docker start $CONT_NAME; \
        echo 'Staging - Docker Deployment Completed.'; \
        exit 0; \
      else \
        echo 'Staging - Image $REGISTRY_URL:$STAGE_VER not found, start building...'; \
        docker stop $CONT_NAME; \
        docker compose -f $COMPOSE_FILE down $COMPOSE_SVC; \
        docker compose -f $COMPOSE_FILE up -d --build $COMPOSE_SVC; \
        docker cp $ENV_FILE $CONT_NAME:$CONT_PATH/.env; \ 
        docker exec $CONT_NAME apt update && apt install -y curl vim plocate iputils-ping net-tools openssh-client git; \
        docker exec $CONT_NAME sh -c "ssh-keyscan -H github.com > ~/.ssh/known_hosts"; \
        docker exec $CONT_NAME git config --global user.email 'rizal@weave.co.id'; \
        docker exec $CONT_NAME git config --global user.name 'rizal'; \
        docker exec $CONT_NAME git config --global credential.helper store; \
        docker exec $CONT_NAME git branch --set-upstream-to=origin/stage stage; \
        docker exec $CONT_NAME git pull origin stage; \
        docker exec $CONT_NAME npm install; \
        docker exec $CONT_NAME npm i sharp; \
        docker exec $CONT_NAME env NODE_OPTIONS="--max_old_space_size=1024" npm run build --prod; \
        docker stop $CONT_NAME; \
        docker start $CONT_NAME; \
        echo 'Staging - Docker Deployment Completed.'; \
      fi"
  artifacts:
    paths:
      - build/

deploy-production:
  stage: Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - .env.devel
        - .env.stage
        - .env.prod
        - .gitlab-ci.yml
      when: never   # Pipeline will not running if the files are in the list was 'changes'.
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always # Pipeline will running if the files are in the list was 'changes'.
  before_script:
    - apt update && apt install -y git && apt install -y vim
    - mkdir -p ~/.ssh
    - echo "$FWA_PROD_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p 9922 $PROD_SSH_CON \
      "echo 'Production - Reset and clean the repository to avoid stale changes in container'; \
      docker exec $CONT_NAME git reset --hard; \
      docker exec $CONT_NAME git clean -fd; \
      echo 'Production - Fetch and reset to match the remote branch'; \
      docker exec $CONT_NAME git fetch --all; \
      docker exec $CONT_NAME git reset --hard origin/main; \
      echo 'Production - Local Repository in container was cleaned.'"
  script:
    - echo "Production - Deployment starting..."
    - mkdir -p ~/.ssh
    - echo "$FWA_PROD_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
    - |
      ssh -o StrictHostKeyChecking=no -p 9922 $PROD_SSH_CON \
      "echo 'Production - Updating the apps from the repository...'; \
      docker ps --filter 'name=$CONT_NAME' --format '{{.Names}}' | grep -w $CONT_NAME > /dev/null; \
      if [ \$? -eq 0 ]; then \
        echo 'Production - Container $CONT_NAME is already running.'; \
        docker exec $CONT_NAME apt update; \
        docker exec $CONT_NAME apt update && apt install -y curl vim plocate iputils-ping net-tools openssh-client git; \
        docker exec $CONT_NAME sh -c "ssh-keyscan -H github.com > ~/.ssh/known_hosts"; \
        docker exec $CONT_NAME git config --global user.email 'rizal@weave.co.id'; \
        docker exec $CONT_NAME git config --global user.name 'rizal'; \
        docker exec $CONT_NAME git config --global credential.helper store; \
        docker exec $CONT_NAME git branch --set-upstream-to=origin/main main; \
        docker exec $CONT_NAME git pull origin main; \
        docker exec $CONT_NAME npm install; \
        docker exec $CONT_NAME npm i sharp; \
        docker exec $CONT_NAME env NODE_OPTIONS="--max_old_space_size=1024" npm run build --prod; \
        docker stop $CONT_NAME; \
        docker start $CONT_NAME; \
        echo 'Production - Docker Deployment Completed.'; \
        exit 0; \
      else \
        echo 'Production - Image $REGISTRY_URL:$PROD_VER not found, starting a container...'; \
        docker stop $CONT_NAME; \
        docker compose -f $COMPOSE_FILE down $COMPOSE_SVC; \
        docker compose -f $COMPOSE_FILE up -d --build $COMPOSE_SVC; \
        docker cp $ENV_FILE $CONT_NAME:$CONT_PATH/.env; \ 
        docker exec $CONT_NAME apt update && apt install -y curl vim plocate iputils-ping net-tools openssh-client git; \
        docker exec $CONT_NAME sh -c "ssh-keyscan -H github.com > ~/.ssh/known_hosts"; \
        docker exec $CONT_NAME git config --global user.email 'rizal@weave.co.id'; \
        docker exec $CONT_NAME git config --global user.name 'rizal'; \
        docker exec $CONT_NAME git config --global credential.helper store; \
        docker exec $CONT_NAME git branch --set-upstream-to=origin/main main; \
        docker exec $CONT_NAME git pull origin main; \
        docker exec $CONT_NAME npm install; \
        docker exec $CONT_NAME npm i sharp; \
        docker exec $CONT_NAME env NODE_OPTIONS="--max_old_space_size=1024" npm run build --prod; \
        docker stop $CONT_NAME; \
        docker start $CONT_NAME; \
        echo 'Production - Docker Deployment Completed.'; \
      fi"
  artifacts:
    paths:
      - build/
  environment:
    name: production

# image-push:
#   stage: Push
#   only:
#     - stage
#   before_script:
#     - apt update && apt install -y git && apt install -y vim
#     - mkdir -p ~/.ssh
#   script:
#     - echo "Deployment starting..."
#   #   - echo "$FWA_PROD_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#   #   - chmod 600 ~/.ssh/id_rsa
#   #   - echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
#   #   - echo "Deploying to production server..."
#   #   - |
#   #     ssh -o StrictHostKeyChecking=no -p 9922 $SRC_SSH_CON \
#   #     "echo 'Push docker image to GitLab registry...'; \
#   #     docker push $REGISTRY_URL:$IMG_VER; \
#   #     echo 'Pushing an docker image completed.'"
#   environment:
#      name: production
